'use client'
import { FormEvent, useState } from 'react'
type Message = { role: 'customer' | 'assistant'; content: string }
export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: 'Hola, soy el asistente de VUNIKO. ¿En qué puedo ayudarte?' }])
  const [input, setInput] = useState(''); const [token, setToken] = useState<string>(); const [loading, setLoading] = useState(false); const [handoff, setHandoff] = useState(false)
  async function send(event: FormEvent) { event.preventDefault(); if (!input.trim() || loading) return; const text = input.trim(); setInput(''); setMessages((m) => [...m, { role: 'customer', content: text }]); setLoading(true); const response = await fetch('/api/chat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message: text, sessionToken: token }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setMessages((m) => [...m, { role: 'assistant', content: data.error ?? 'No pude responder ahora.' }]); return }; setToken(data.sessionToken); setMessages((m) => [...m, { role: 'assistant', content: data.messages.at(-1).content }]); if (data.handoff) setHandoff(true) }
  return <main className="mx-auto flex min-h-screen max-w-xl flex-col bg-white px-5 py-8 text-slate-900"><div className="mb-6"><p className="text-sm font-semibold text-indigo-600">VUNIKO AI CRM</p><h1 className="text-3xl font-bold">Asistente inteligente</h1><p className="mt-2 text-sm text-slate-500">Conversa con tus clientes desde tu web con IA y conserva el historial en VUNIKO.</p></div><section className="flex flex-1 flex-col gap-3 rounded-2xl border bg-slate-50 p-4">{messages.map((m, i) => <div key={i} className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${m.role === 'customer' ? 'ml-auto bg-indigo-600 text-white' : 'bg-white shadow-sm'}`}>{m.content}</div>)}{loading && <div className="text-sm text-slate-400">Escribiendo…</div>}{handoff && <div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-700">La conversación fue derivada al equipo para continuar la atención.</div>}</section><form onSubmit={send} className="mt-4 flex gap-2"><input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Escribe tu mensaje…" className="min-w-0 flex-1 rounded-xl border px-4 py-3 outline-none focus:border-indigo-500"/><button className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-50" disabled={loading}>Enviar</button></form></main>
}
